# Generated by Django 2.2.4 on 2019-08-09 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_shippingmethod_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
