# Generated by Django 2.2.4 on 2019-08-24 14:45

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_shippingmethod_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping'), ('percentage', 'Percentage based shipping')], max_length=30),
        ),
    ]
