# Generated by Django 2.2.4 on 2019-08-25 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0018_auto_20190824_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
